name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: assembleRelease with Gradle
        run: ./gradlew assembleRelease

      - name: assembleDebug with Gradle
        run: ./gradlew assembleDebug

      - name: Get tag name
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: app/build/outputs/apk/release/ModManager-release-${{ evn.TAG_NAME }}.apk

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: app/build/outputs/apk/debug/ModManager-release-${{ evn.TAG_NAME }}.apk
