name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: assembleRelease with Gradle
        run: ./gradlew assembleRelease

      - name: assembleDebug with Gradle
        run: ./gradlew assembleDebug

      - name: Upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: app/build/outputs/apk/release/ModManager-release.apk

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: app/build/outputs/apk/debug/ModManager-debug.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download release apk
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Create GitHub Release
        id: create_release  # 添加ID以便引用
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用 create_release 步骤的输出
          asset_path: app/build/outputs/apk/release/ModManager-release.apk
          asset_name: ModManager-release.apk
          asset_content_type: application/vnd.android.package-archive
