name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Assemble Release with Gradle
        run: ./gradlew assembleRelease

      - name: Assemble Debug with Gradle
        run: ./gradlew assembleDebug

      - name: List APK files
        run: ls -R app/build/outputs/apk/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload Release APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/ModManager-release.apk
          asset_name: ModManager-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Debug APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/ModManager-release.apk
          asset_name: ModManager-debug.apk
          asset_content_type: application/vnd.android.package-archive
