name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Assemble Release with Gradle
        run: ./gradlew assembleRelease

      - name: List APK files
        run: ls -R app/build/outputs/apk/

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}.
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/ModManager-release-${{ github.ref_name }}.apk
